language: node_js  #设置语言

sudo: false

node_js:
  - '6' 

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g hexo-cli  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo generate  #生成

after_script:
  - cp CNAME ./public
  - cd ./public
  - git init
  - git config user.name "START_END"  #修改name
  - git config user.email "858965877@qq.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称
env:
 global:
   - GH_REF: github.com/StartEnd/StartEnd.github.io.git  #设置GH_REF，注意更改yourname
