language: node_js  #设置语言

sudo: false

node_js:
  - "7.6" 

branches:
  only:
    - master

cache:
    #  apt: true
    #yarn: true
    #directories:
    #- node_modules

before_install: 
  - git config user.name "START_END"  #修改name
  - git config user.email "858965877@qq.com"  #修改email
  # 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install
  

install:
    # 不用yarn的话这里改成 npm i 即可
  - yarn
    # - npm install -g hexo-cli  #安装hexo及插件
    # - npm install 
script:
  - hexo clean  #清除
  - hexo generate  #生成

after_script:
  - cp CNAME ./public
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称
env:
 global:
   - GH_REF: github.com/StartEnd/StartEnd.github.io.git  #设置GH_REF，注意更改yourname
