# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Mr. Song's blog
subtitle: 完成比完美更重要
description: Developer
author: 水煮冰
language: zh-CN
timezone: UTC
footer: Make everything as simple as possible,but not simpler

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: yuanchunxiang.com
root: /
permalink: :category/:abbrlink/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
archive_generator:
  per_page: 20  #为0时表示不分页全展示
  yearly: true  #按年生成归档
  monthly: true #按月生成归档
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss



tag_generator:
  per_page: 10


# Pagination
## Set per_page to 0 to disable pagination
#per_page: 10
#pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next-reloaded ## hexo-theme-next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:StartEnd/StartEnd.github.io.git
  branch: master

# Search 
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
  
# 自动生成sitemap
sitemap:
  path: sitemap.xml

baidusitemap:
  path: baidusitemap.xml
  
symbols_count_time:
  symbols: true
  time: true
  total_symbols: false
  total_time: false
  
	
# 图片懒加载
lazyload:
  enable: true 
  onlypost: false
  loadingImg: /images/loading.gif 
  
# hexo-neat 静态资源压缩
neat_enable: true 
neat_html:
  enable: true
  exclude: 
neat_css:
  enable: false
  exclude:
    - '*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'
	
	
# hexo-generator-amp
# 为 Hexo 博客生成 AMP 页面，加速优化移动端访问

generator_amp:
  templateDir:  amp-template
  assetDistDir: amp-dist
  logo:
    path:   sample/sample-logo.png
    width:  600
    height: 60
  substituteTitleImage:
    path:   sample/sample-substituteTitleImage.png
    width:  1024
    height: 800
  warningLog: false   # To display warning, please set true.
  
  
 # 生成链接
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
  
  
  
